### ISSUE TITLE
ERROR WHILE DELETING FILE

### ISSUE THREAD

**Issue by joalricha869** [joalricha869/PyPrompt#5]
Traceback (most recent call last):
  File "main.py", line 409, in <module>
    main()
  File "main.py", line 222, in main
    whatiscommand()
  File "main.py", line 138, in whatiscommand
    main()
  File "main.py", line 222, in main
    whatiscommand()
  File "main.py", line 213, in whatiscommand
    main(current_dir)
TypeError: main() takes 0 positional arguments but 1 was given

**Comment by joalricha869** [comment]
Fixed this more than 3 updates before. also why did i open up an issue myself (i am such a noob)
